### ISSUE TITLE
Invalid login form

### ISSUE THREAD

**Issue by usertgt** [slims/slims9_bulian#131]
Hi,
I installed Slims library management through softaculous on my wordpress website. All was working fine for few days and then it started showing error on the log in page. Once i enter the admin or staff or librarian user &  pass . It pops up an error which says "INVALID LOGIN FORM" and does not log in. Can i please get some support on this

**laptop 
 - OS: [Windows 8]
 - Browser [chrome]

**Comment by kennscott21** [comment]
Hi,

We are also having the same issue which occurred when our host moved us to a new server.  Everything worked great on the old server, but now on a new server with a newer version of PHP and SQL we are unable to login (we can see the catalog and details of the library online, but we receive the INVALID LOGIN FORM error when we try to login to administer the library).  

In the error logs we receive "PHP Warning:  session_start(): open(/var/cpanel/php/sessions/ea-php70/sess_0d8001ba665650c5a628d3e0e268115c, O_RDWR) failed: No such file or directory (2) in *******/index.php on line 35" and "PHP Warning:  session_start(): Failed to read session data: files (path: /var/cpanel/php/sessions/ea-php70) in ****/index.php on line 35"

We also tried doing a fresh install from Softaculous but receive the INVALID LOGIN FORM error when trying to setup the library.  We love SLIMS and it's been great for our small charitable nonprofit school in Africa, but now we can't use it.  If anyone can help us, we would sure appreciate it.  Thank you to all of the developers on this project, who have created such a great tool!

**Comment by drajathasan** [comment]
"INVALID LOGIN FORM" means that your login form does not contain CSRF Tokens. This is a security feature since the release of SLiMS 9. All public forms are guarded with CSRF mechanism, making your public forms like Login Form, Comment Form safe from CSRF Attacks.

"INVALID LOGIN FORM" problem causes:
1. You have opened more than one tab of the SLiMS Login page.
2. Your web server cannot generate $_SESSION due to write permissions etc.
3. Hosting your storage exceeds the size limit.

Solution :
1. Make sure your web server can create session
2. Make sure your hosting disk not exceeds the size limit.

**Comment by kennscott21** [comment]
@drajathasan thank you so much for your help!  I messaged our web host with your feedback and it turned out that the wrong path was copied for the PHP session in session.save_path when we switched servers.  Your guidance about the web server not generating the session definitely pointed us in the right direction.  Now it is working great and we're so excited for our students at our little school in Africa to be able to start using SLiMS.  We really appreciate all the work your doing on this really amazing project!
