### ISSUE TITLE
Error 500 after editing default theme parameter

### ISSUE THREAD

**Issue by mahdimadineh** [slims/slims9_bulian#15]
Hello

After editing the theme parameter in admin panel, I encountered an error.
Error log:
PHP Warning:  require(//index_template.inc.php): failed to open stream: No such file or directory in /home2/my site/public_html/lib/index.php on line 110

PHP Fatal error:  require(): Failed opening required '//index_template.inc.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home2/my site/public_html/lib/index.php on line 110

My language is Persian.

Thansk

**Comment by buitenzorg812** [comment]
which theme parameter did you change?

**Comment by mahdimadineh** [comment]
I haven't exactly tested which parameter causes this error.
But i'm sure that every time i changed one of the parameters or changed some part of the template, I had encountered this error and I had to reinstall the site.

**Comment by juansts** [comment]
I'd like to confirm the reported bug.

**Steps to reproduce the behavior**:
1. Login to admin page.
2. Go to System > Theme > Default > Customize
3. In the Map Description add new line by pressing the **ENTER** key.
![slims900-mapdescription-02-newparagraph](https://user-images.githubusercontent.com/760035/83323950-23ebd280-a28c-11ea-9bf9-b58308b01c00.jpg)

4. Save Settings
5. Reload homepage and you will get HTTP ERROR 500.

**Steps to recover** (instead of reinstalling):
1. Open the MySQL database. 
2. Go to table 'setting'
3. WHERE setting_name is 'template', UPDATE the setting_value to
`a:2:{s:5:"theme";s:7:"default";s:3:"css";s:0:"";}`
4. Reload homepage.

**System information**:
Slims 9.0.0
Operating System	: Linux lamp 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64
OS Architecture	: x86_64 64 bit
Web Server	: Apache
PHP version	: 7.3.14-1~deb10u1
MySQL Database version	: 5.5.5-10.3.22-MariaDB-0+deb10u1
MySQL Client version	: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

**Comment by idoalit** [comment]
Fixed [c3cdf20](https://github.com/slims/slims9_bulian/commit/c3cdf201625deaa0b04405a0b5fbd072948ed4ee)
